### ISSUE TITLE
a little question

### ISSUE THREAD

**Issue by 5misakamikoto5** [CMA-ES/plotting-cma-data#1]
Hello,I install cma-3.2.2 and run the cma.plot().But it comes out with an error:
AttributeError: 'CMADataLogger' object has no attribute 'f'
How can I solve it

**Comment by nikohansen** [comment]
This is expected, because `cma.plot()` only works after an optimization has been run in the same folder. Before, there is nothing to plot. `cma.plot('./')` plots data from the current folder (the default output folder of `pycma` is `outcmaes/`). Consider to have a look at `help(cma.plot)` or `help(cma.CMADataLogger)` or [this notebook](https://github.com/CMA-ES/pycma/blob/master/notebooks/notebook-usecases-basics.ipynb).
